package com.company.skillplatform.notification.enums;

public enum NotificationType {
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    SESSION_REGISTERED,
    SESSION_REGISTRATION_CANCELED,
    SESSION_COMPLETED,
    SESSION_UNATTENDED,
    SESSION_LIVE,
    SESSION_CANCELED,
    SESSION_DEPARTMENT_CONFLICT_WARNING,
    SESSION_UPDATED,
    SESSION_REMINDER_HOST_24H,
    SESSION_REMINDER_ATTENDEE_1H,
    POST_LIKED,
    POST_COMMENTED,
    SESSION_FEEDBACK_REQUEST,
    SESSION_RECORDING_ADDED,
    USER_ROLE_UPDATED,
    MENTOR_BADGE_REVIEW_REQUESTED,
    MENTOR_BADGE_APPROVED,
    MENTOR_BADGE_REJECTED,
    SESSION_FEEDBACK_ADDED,
    SESSION_FEEDBACK_UPDATED,
    POST_UPDATED


}

